/**
 * @fileoverview gRPC-Web generated client stub for dnv.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: proto/dnv.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.dnv = {};
proto.dnv.v1 = require('./dnv_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dnv.v1.DnvClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dnv.v1.DnvPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dnv.v1.GetRunScript,
 *   !proto.dnv.v1.ScriptResult>}
 */
const methodDescriptor_Dnv_RunScript = new grpc.web.MethodDescriptor(
  '/dnv.v1.Dnv/RunScript',
  grpc.web.MethodType.UNARY,
  proto.dnv.v1.GetRunScript,
  proto.dnv.v1.ScriptResult,
  /**
   * @param {!proto.dnv.v1.GetRunScript} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dnv.v1.ScriptResult.deserializeBinary
);


/**
 * @param {!proto.dnv.v1.GetRunScript} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dnv.v1.ScriptResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dnv.v1.ScriptResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dnv.v1.DnvClient.prototype.runScript =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dnv.v1.Dnv/RunScript',
      request,
      metadata || {},
      methodDescriptor_Dnv_RunScript,
      callback);
};


/**
 * @param {!proto.dnv.v1.GetRunScript} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dnv.v1.ScriptResult>}
 *     Promise that resolves to the response
 */
proto.dnv.v1.DnvPromiseClient.prototype.runScript =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dnv.v1.Dnv/RunScript',
      request,
      metadata || {},
      methodDescriptor_Dnv_RunScript);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dnv.v1.GetMermaidRequest,
 *   !proto.dnv.v1.Mermaid>}
 */
const methodDescriptor_Dnv_GetMermaid = new grpc.web.MethodDescriptor(
  '/dnv.v1.Dnv/GetMermaid',
  grpc.web.MethodType.UNARY,
  proto.dnv.v1.GetMermaidRequest,
  proto.dnv.v1.Mermaid,
  /**
   * @param {!proto.dnv.v1.GetMermaidRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dnv.v1.Mermaid.deserializeBinary
);


/**
 * @param {!proto.dnv.v1.GetMermaidRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dnv.v1.Mermaid)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dnv.v1.Mermaid>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dnv.v1.DnvClient.prototype.getMermaid =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dnv.v1.Dnv/GetMermaid',
      request,
      metadata || {},
      methodDescriptor_Dnv_GetMermaid,
      callback);
};


/**
 * @param {!proto.dnv.v1.GetMermaidRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dnv.v1.Mermaid>}
 *     Promise that resolves to the response
 */
proto.dnv.v1.DnvPromiseClient.prototype.getMermaid =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dnv.v1.Dnv/GetMermaid',
      request,
      metadata || {},
      methodDescriptor_Dnv_GetMermaid);
};


module.exports = proto.dnv.v1;

